-- Digital Pet File - Default Admin Seed
-- NOTE:
-- 1) Replace the password hash with a bcrypt hash generated by your backend utility.
-- 2) Keep role as 'admin'.

insert into public.users (
  role,
  username,
  password_hash,
  parent_name,
  phone_number
)
values (
  'admin',
  'eternaadmin',
  '$2b$12$wY/m6Fd6Zni7SCeJ5K3JOO/mE7lQQXRNS8TJwCI3TmhWtJjrT2Tm2',
  'System Admin',
  '+10000000000'
)
on conflict (username) do nothing;
