-- Digital Pet File - Default Admin Seed
-- NOTE:
-- 1) Replace the password hash with a bcrypt hash generated by your backend utility.
-- 2) Keep role as 'admin'.

insert into public.users (
  role,
  username,
  password_hash,
  parent_name,
  phone_number
)
values (
  'admin',
  'admin_master',
  '$2b$12$9RvkL6v4Q1j2O3hM9zIf5eXQ8Lax4VYdMG2at2k1p9N03fW8n2F7u',
  'System Admin',
  '+10000000000'
)
on conflict (username) do nothing;
